### ISSUE TITLE
Undefined Index: HTTPS; Undefined variable: legacy

### ISSUE THREAD

**Issue by bigandy** [WP-API/example-client#1]
Just installed and trying it out. 

Ran `php -S 0.0.0.0:8080 www/index.php` and get the following in terminal: 

[Mon Dec  7 13:47:11 2015] PHP Notice:  Undefined index: HTTPS in /Users/andrew/Sites/example-client/www/helpers.php on line 18
[Mon Dec  7 13:47:11 2015] PHP Notice:  Undefined variable: legacy in /Users/andrew/Sites/example-client/www/discovery-form.php on line 14

**Comment by tollmanz** [comment]
+1

**Comment by rmccue** [comment]
Huh. What version of PHP are you running?

**Comment by tollmanz** [comment]
I see this on 5.6.13.

**Comment by rmccue** [comment]
Thanks, fixed now :)
